// Generated by CoffeeScript 1.10.0
(function() {
  var demoText, getSeq, logoSettings, makeObj;

  demoText = ['FALCON'.split(''), '2K17'.split('')];

  logoSettings = {
    size: 140,
    margin: 15,
    fontSize: 85,
    perspective: 450
  };

  makeObj = function(a) {
    var i, j, len1, o, v;
    o = {};
    for (i = j = 0, len1 = a.length; j < len1; i = ++j) {
      v = a[i];
      o['letter' + i] = a;
    }
    return o;
  };

  getSeq = function(a, reverse, random) {
    var i, j, len, len1, o, p, v;
    o = {};
    len = a.length;
    for (i = j = 0, len1 = a.length; j < len1; i = ++j) {
      v = a[i];
      if (reverse) {
        p = len - i - 1;
      } else if (random) {
        p = Math.floor(Math.random() * len);
      } else {
        p = i;
      }
      o['letter' + i] = a[p];
    }
    return o;
  };

  document.addEventListener('DOMContentLoaded', function() {
    var action, fn, hexaPhoto, hexaTime, i, j, len1, logos, n, photoControls, ref, textDemos;
    logos = document.getElementsByClassName('logo');
    textDemos = (function() {
      var j, results;
      results = [];
      for (n = j = 0; j <= 1; n = ++j) {
        results.push(new HexaFlip(logos[n], makeObj(demoText[n]), logoSettings));
      }
      return results;
    })();
    setTimeout(function() {
      var k;
      for (n = k = 0; k <= 1; n = ++k) {
        textDemos[n].setValue(getSeq(demoText[n], true));
      }
      return null;
    }, 0);
    setTimeout(function() {
      var k;
      for (n = k = 0; k <= 1; n = ++k) {
        textDemos[n].setValue(getSeq(demoText[n]));
      }
      return null;
    }, 1000);
})}).call(this);

//# sourceMappingURL=demo.js.map
